### ISSUE TITLE
Зачёт 20240528

### ISSUE THREAD

**Issue by alexanderustinov** [alexanderustinov/2023-bi-python-2-test#4]
Как-то небрежно всё получилось. Комментарии в порядке сдачи.

Ангелина.  
1. флаг получился
2. именование файла программы и его расположение провалено
3. pylint немного провален
```python
(venv) ustinov@player ~/tmp/test/shishkina $ pylint _1_.py --generated-members='SVGSurface|Context'
************* Module _1_
_1_.py:1:0: C0114: Missing module docstring (missing-module-docstring)
_1_.py:2:0: C0411: standard import "math.pi" should be placed before third party import "cairo" (wrong-import-order)
_1_.py:2:0: W0611: Unused pi imported from math (unused-import)

------------------------------------------------------------------
Your code has been rated at 7.86/10 (previous run: 7.86/10, +0.00)
```

Сергей.
1. У флага есть промах
![2024-05-28-174734_835x547_scrot](https://github.com/alexanderustinov/2023-bi-python-2-test/assets/5900727/305e0b43-c848-4085-8668-b42b060d3d8e)
2. в задании просил программу класть в директорию, но хоть фамилией подписали py-файл; почти не провалено
3. pylint :ok_hand: 
```python
(venv) ustinov@player ~/tmp/test/esikov $ pylint EsikovSD.py --generated-members='SVGSurface|Context'
************* Module EsikovSD
EsikovSD.py:1:0: C0114: Missing module docstring (missing-module-docstring)
EsikovSD.py:1:0: C0103: Module name "EsikovSD" doesn't conform to snake_case naming style (invalid-name)

------------------------------------------------------------------
Your code has been rated at 8.89/10 (previous run: 8.89/10, +0.00)
```

Анна.
1. визуальные проблемы, на мой взгляд, весомее, чем у Сергея + сделан `png` вместо прошеного `svg`
2. именование и расположение не выдержано
3. ~~pylint провален заметнее прочих~~ нашёл несколько кусков ключа командной строки, которые стоит добавлять из-за ~~богатого внутреннего мира~~ устройства модуля pycairo. pylint :ok_hand: 
```python
ustinov@player ~/tmp/test/maslovskaya $ pylint teeest.py --generated-members='SVGSurface|Context|ImageSurface|Format'
************* Module teeest
teeest.py:1:0: C0114: Missing module docstring (missing-module-docstring)
teeest.py:6:0: C0103: Constant name "x" doesn't conform to UPPER_CASE naming style (invalid-name)
teeest.py:7:0: C0103: Constant name "y" doesn't conform to UPPER_CASE naming style (invalid-name)
teeest.py:24:0: C0103: Constant name "x" doesn't conform to UPPER_CASE naming style (invalid-name)
teeest.py:33:0: C0103: Constant name "x" doesn't conform to UPPER_CASE naming style (invalid-name)
teeest.py:45:0: C0103: Constant name "output_filename" doesn't conform to UPPER_CASE naming style (invalid-name)
teeest.py:2:0: C0411: standard import "os" should be placed before third party import "cairo" (wrong-import-order)

------------------------------------------------------------------
Your code has been rated at 8.25/10 (previous run: 5.75/10, +2.50)
```

Подумаю немного обо всём этом.

@Grosperon @Extazy-b @Alsh111

**Comment by Extazy-b** [comment]
Любопытно про промах во флаге, учитывая что при предпросмотре рисовалось все ровно
Возможно браузер как-то обрезал края...

**Comment by alexanderustinov** [comment]
> Любопытно про промах во флаге, учитывая что при предпросмотре рисовалось все ровно Возможно браузер как-то обрезал края...

Может, поскроллить забыл :)

**Comment by alexanderustinov** [comment]
Ангелина, Сергей - зачёт.
Анна - незачёт.
